org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.3-rc-2
minecraft_dependency=26.3-rc.2
loader_version=0.19.5
loom_version=1.17.20
fabric_api_version=0.160.4+26.3
fabric_api_dependency=0.160.4

# Mod Properties
mod_version=1.2.0-rc.2
maven_group=me.justbecause.fastpaintings
